// Fake traders for demo mode: simulated market participants that generate
// realistic order flow against synthetic books. Each trader archetype follows
// a distinct behavioral pattern with randomized sizing and timing.

const std = @import("std");
const L2Book = @import("orderbook").L2Book;
const Level = @import("orderbook").Level;
const Side = @import("orderbook").Side;

/// A single trade generated by a fake trader.
pub const FakeTrade = struct {
    instrument_idx: u8,
    side: TradeSide,
    quantity: i64,
    price: i64,
    tag: [8]u8,
    tag_len: u8,
};

pub const TradeSide = enum { buy, sell };

/// Result buffer for trades generated in a single tick.
pub const TradeBuffer = struct {
    trades: [MAX_TRADES_PER_TICK]FakeTrade,
    count: u8,

    pub fn init() TradeBuffer {
        return .{
            .trades = undefined,
            .count = 0,
        };
    }

    fn push(self: *TradeBuffer, instrument_idx: u8, side: TradeSide, quantity: i64, price: i64, comptime tag: []const u8) void {
        if (self.count < MAX_TRADES_PER_TICK) {
            var t: FakeTrade = .{
                .instrument_idx = instrument_idx,
                .side = side,
                .quantity = quantity,
                .price = price,
                .tag = undefined,
                .tag_len = @intCast(tag.len),
            };
            @memcpy(t.tag[0..tag.len], tag);
            self.trades[self.count] = t;
            self.count += 1;
        }
    }
};

const MAX_TRADES_PER_TICK = 32;
const NUM_INSTRUMENTS = 8;

// ─── Trader archetype: Market Maker ──────────────────────────────────────────
// Places bids and asks near the spread. Skews quotes based on inventory to
// flatten position. Trades frequently with small sizes.

const MarketMaker = struct {
    inventory: [NUM_INSTRUMENTS]i64, // net position per instrument
    max_inventory: i64,
    base_qty: i64,
    tick_interval: u16, // trade every N ticks
    spread_ticks: u8, // how many tick-sizes from mid to quote

    fn init(base_qty: i64, max_inv: i64, interval: u16, spread: u8) MarketMaker {
        return .{
            .inventory = std.mem.zeroes([NUM_INSTRUMENTS]i64),
            .max_inventory = max_inv,
            .base_qty = base_qty,
            .tick_interval = interval,
            .spread_ticks = spread,
        };
    }

    fn onTick(self: *MarketMaker, tick: u64, rand: std.Random, books: *const [8]L2Book, buf: *TradeBuffer) void {
        if (tick % self.tick_interval != 0) return;

        // Pick 1-2 random instruments to quote
        const num_instruments = rand.intRangeAtMost(u8, 1, 2);
        for (0..num_instruments) |_| {
            const idx = rand.intRangeLessThan(u8, 0, NUM_INSTRUMENTS);
            const book = &books[idx];
            const mid = book.midPrice() orelse continue;
            const spread = book.spread() orelse continue;
            const half_spread = @max(@divTrunc(spread, 2), 1);

            // Randomize quantity: base_qty * [0.5, 2.0]
            const qty_mult = rand.intRangeAtMost(u16, 50, 200);
            const qty = @divTrunc(self.base_qty * @as(i64, qty_mult), 100);

            // Skew: if long, prefer selling; if short, prefer buying
            const inv = self.inventory[idx];
            const inv_ratio = if (self.max_inventory > 0)
                @divTrunc(inv * 100, self.max_inventory)
            else
                @as(i64, 0);

            // Decide side based on inventory skew + randomness
            const rand_bias = rand.intRangeAtMost(i64, -30, 30);
            const should_sell = (inv_ratio + rand_bias) > 10;

            if (should_sell) {
                const price = mid + half_spread;
                buf.push(idx, .sell, qty, price, "MM");
                self.inventory[idx] -= qty;
            } else {
                const price = mid - half_spread;
                buf.push(idx, .buy, qty, price, "MM");
                self.inventory[idx] += qty;
            }
        }
    }
};

// ─── Trader archetype: Momentum Trader ───────────────────────────────────────
// Tracks short-term price direction using a simple EMA difference.
// Buys when price is trending up, sells when trending down.

const MomentumTrader = struct {
    fast_ema: [NUM_INSTRUMENTS]i64, // short-period EMA
    slow_ema: [NUM_INSTRUMENTS]i64, // longer-period EMA
    position: [NUM_INSTRUMENTS]i64,
    max_position: i64,
    base_qty: i64,
    tick_interval: u16,
    initialized: bool,

    fn init(base_qty: i64, max_pos: i64, interval: u16) MomentumTrader {
        return .{
            .fast_ema = std.mem.zeroes([NUM_INSTRUMENTS]i64),
            .slow_ema = std.mem.zeroes([NUM_INSTRUMENTS]i64),
            .position = std.mem.zeroes([NUM_INSTRUMENTS]i64),
            .max_position = max_pos,
            .base_qty = base_qty,
            .tick_interval = interval,
            .initialized = false,
        };
    }

    fn onTick(self: *MomentumTrader, tick: u64, rand: std.Random, books: *const [8]L2Book, buf: *TradeBuffer) void {
        // Update EMAs every tick, but only trade on interval
        for (0..NUM_INSTRUMENTS) |i| {
            const mid = books[i].midPrice() orelse continue;
            if (!self.initialized) {
                self.fast_ema[i] = mid;
                self.slow_ema[i] = mid;
            } else {
                // Fast EMA: alpha ~0.1 (scaled integer: new = old + (mid - old) / 10)
                self.fast_ema[i] += @divTrunc(mid - self.fast_ema[i], 10);
                // Slow EMA: alpha ~0.02 (new = old + (mid - old) / 50)
                self.slow_ema[i] += @divTrunc(mid - self.slow_ema[i], 50);
            }
        }
        self.initialized = true;

        if (tick % self.tick_interval != 0) return;

        // Pick one instrument to trade
        const idx = rand.intRangeLessThan(u8, 0, NUM_INSTRUMENTS);
        const book = &books[idx];
        const mid = book.midPrice() orelse return;

        const signal = self.fast_ema[idx] - self.slow_ema[idx];
        // Threshold: need a meaningful crossover to trade
        const threshold = @divTrunc(mid, 10_000); // 1 bps of mid price

        const qty_mult = rand.intRangeAtMost(u16, 60, 150);
        const qty = @divTrunc(self.base_qty * @as(i64, qty_mult), 100);

        if (signal > threshold and self.position[idx] < self.max_position) {
            // Uptrend: buy
            const best_ask = book.bestAsk() orelse return;
            buf.push(idx, .buy, qty, best_ask.price, "MOM");
            self.position[idx] += qty;
        } else if (signal < -threshold and self.position[idx] > -self.max_position) {
            // Downtrend: sell
            const best_bid = book.bestBid() orelse return;
            buf.push(idx, .sell, qty, best_bid.price, "MOM");
            self.position[idx] -= qty;
        }
    }
};

// ─── Trader archetype: Mean Reversion Trader ─────────────────────────────────
// Buys when price drops below a moving average band, sells when above.
// Classic contrarian strategy.

const MeanRevTrader = struct {
    ma: [NUM_INSTRUMENTS]i64, // simple moving average (EMA approximation)
    position: [NUM_INSTRUMENTS]i64,
    max_position: i64,
    base_qty: i64,
    tick_interval: u16,
    band_bps: i64, // band width in basis points (e.g., 30 = 0.3%)
    initialized: bool,

    fn init(base_qty: i64, max_pos: i64, interval: u16, band: i64) MeanRevTrader {
        return .{
            .ma = std.mem.zeroes([NUM_INSTRUMENTS]i64),
            .position = std.mem.zeroes([NUM_INSTRUMENTS]i64),
            .max_position = max_pos,
            .base_qty = base_qty,
            .tick_interval = interval,
            .band_bps = band,
            .initialized = false,
        };
    }

    fn onTick(self: *MeanRevTrader, tick: u64, rand: std.Random, books: *const [8]L2Book, buf: *TradeBuffer) void {
        // Update MA every tick
        for (0..NUM_INSTRUMENTS) |i| {
            const mid = books[i].midPrice() orelse continue;
            if (!self.initialized) {
                self.ma[i] = mid;
            } else {
                // Slow MA: alpha ~0.01
                self.ma[i] += @divTrunc(mid - self.ma[i], 100);
            }
        }
        self.initialized = true;

        if (tick % self.tick_interval != 0) return;

        const idx = rand.intRangeLessThan(u8, 0, NUM_INSTRUMENTS);
        const book = &books[idx];
        const mid = book.midPrice() orelse return;
        const ma = self.ma[idx];
        if (ma == 0) return;

        // Deviation from MA in basis points
        const deviation_bps = @divTrunc((mid - ma) * 10_000, ma);

        const qty_mult = rand.intRangeAtMost(u16, 50, 180);
        const qty = @divTrunc(self.base_qty * @as(i64, qty_mult), 100);

        if (deviation_bps < -self.band_bps and self.position[idx] < self.max_position) {
            // Price below MA band: buy the dip
            const best_ask = book.bestAsk() orelse return;
            buf.push(idx, .buy, qty, best_ask.price, "MEAN");
            self.position[idx] += qty;
        } else if (deviation_bps > self.band_bps and self.position[idx] > -self.max_position) {
            // Price above MA band: sell the rally
            const best_bid = book.bestBid() orelse return;
            buf.push(idx, .sell, qty, best_bid.price, "MEAN");
            self.position[idx] -= qty;
        }
    }
};

// ─── Trader archetype: Noise Trader ──────────────────────────────────────────
// Random direction and timing. Simulates uninformed retail flow.

const NoiseTrader = struct {
    position: [NUM_INSTRUMENTS]i64,
    max_position: i64,
    base_qty: i64,
    trade_probability: u8, // out of 100: chance of trading each tick

    fn init(base_qty: i64, max_pos: i64, prob: u8) NoiseTrader {
        return .{
            .position = std.mem.zeroes([NUM_INSTRUMENTS]i64),
            .max_position = max_pos,
            .base_qty = base_qty,
            .trade_probability = prob,
        };
    }

    fn onTick(self: *NoiseTrader, _: u64, rand: std.Random, books: *const [8]L2Book, buf: *TradeBuffer) void {
        // Random chance to trade each tick
        if (rand.intRangeAtMost(u8, 0, 99) >= self.trade_probability) return;

        const idx = rand.intRangeLessThan(u8, 0, NUM_INSTRUMENTS);
        const book = &books[idx];

        const qty_mult = rand.intRangeAtMost(u16, 30, 250);
        const qty = @divTrunc(self.base_qty * @as(i64, qty_mult), 100);

        // Bias slightly toward flattening position
        const pos = self.position[idx];
        const flat_bias: i64 = if (pos > 0) 40 else if (pos < 0) 60 else 50;
        const roll = rand.intRangeAtMost(i64, 0, 99);
        const wants_buy = roll >= flat_bias;

        if (wants_buy) {
            const best_ask = book.bestAsk() orelse return;
            // Sometimes use a limit deeper in the book
            const offset: i64 = @intCast(rand.intRangeAtMost(u64, 0, 3));
            const price = best_ask.price + offset * 100_000;
            if (self.position[idx] < self.max_position) {
                buf.push(idx, .buy, qty, price, "NOISE");
                self.position[idx] += qty;
            }
        } else {
            const best_bid = book.bestBid() orelse return;
            const offset: i64 = @intCast(rand.intRangeAtMost(u64, 0, 3));
            const price = best_bid.price - offset * 100_000;
            if (self.position[idx] > -self.max_position) {
                buf.push(idx, .sell, qty, price, "NOISE");
                self.position[idx] -= qty;
            }
        }
    }
};

// ─── Trader archetype: Whale ─────────────────────────────────────────────────
// Infrequent, large trades that create visible price impact.
// Picks a direction and builds over several ticks (iceberg style).

const WhaleTrader = struct {
    position: [NUM_INSTRUMENTS]i64,
    max_position: i64,
    base_qty: i64, // much larger than other traders
    // Active iceberg state
    iceberg_instrument: u8,
    iceberg_side: TradeSide,
    iceberg_remaining: i64,
    iceberg_slice_qty: i64,
    cooldown: u16, // ticks until next iceberg can start
    min_cooldown: u16,

    fn init(base_qty: i64, max_pos: i64, cooldown: u16) WhaleTrader {
        return .{
            .position = std.mem.zeroes([NUM_INSTRUMENTS]i64),
            .max_position = max_pos,
            .base_qty = base_qty,
            .iceberg_instrument = 0,
            .iceberg_side = .buy,
            .iceberg_remaining = 0,
            .iceberg_slice_qty = 0,
            .cooldown = cooldown / 2, // start partway through so first trade isn't immediate
            .min_cooldown = cooldown,
        };
    }

    fn onTick(self: *WhaleTrader, _: u64, rand: std.Random, books: *const [8]L2Book, buf: *TradeBuffer) void {
        // If we have an active iceberg, drip out slices
        if (self.iceberg_remaining > 0) {
            const book = &books[self.iceberg_instrument];
            // Add jitter: 70% chance to send a slice this tick
            if (rand.intRangeAtMost(u8, 0, 99) < 30) return;

            const slice = @min(self.iceberg_slice_qty, self.iceberg_remaining);
            const price = switch (self.iceberg_side) {
                .buy => if (book.bestAsk()) |a| a.price else return,
                .sell => if (book.bestBid()) |b| b.price else return,
            };
            buf.push(self.iceberg_instrument, self.iceberg_side, slice, price, "WHALE");
            self.iceberg_remaining -= slice;
            switch (self.iceberg_side) {
                .buy => self.position[self.iceberg_instrument] += slice,
                .sell => self.position[self.iceberg_instrument] -= slice,
            }
            return;
        }

        // Cooldown between icebergs
        if (self.cooldown > 0) {
            self.cooldown -= 1;
            return;
        }

        // Start a new iceberg
        const idx = rand.intRangeLessThan(u8, 0, NUM_INSTRUMENTS);
        const book = &books[idx];
        _ = book.midPrice() orelse return;

        // Total size: base_qty * [1.0, 3.0]
        const size_mult = rand.intRangeAtMost(u16, 100, 300);
        const total_qty = @divTrunc(self.base_qty * @as(i64, size_mult), 100);

        // Pick direction: bias toward flattening, else random
        const pos = self.position[idx];
        const side: TradeSide = if (pos > @divTrunc(self.max_position, 2))
            .sell
        else if (pos < -@divTrunc(self.max_position, 2))
            .buy
        else if (rand.boolean())
            .buy
        else
            .sell;

        // Slice into 5-15 pieces
        const num_slices: i64 = rand.intRangeAtMost(i64, 5, 15);

        self.iceberg_instrument = idx;
        self.iceberg_side = side;
        self.iceberg_remaining = total_qty;
        self.iceberg_slice_qty = @max(@divTrunc(total_qty, num_slices), 1);
        self.cooldown = self.min_cooldown + rand.intRangeAtMost(u16, 0, self.min_cooldown / 2);
    }
};

// ─── Pool: manages all fake traders ──────────────────────────────────────────

pub const FakeTraderPool = struct {
    // Multiple instances of each archetype for diversity
    market_makers: [3]MarketMaker,
    momentum_traders: [2]MomentumTrader,
    mean_rev_traders: [2]MeanRevTrader,
    noise_traders: [4]NoiseTrader,
    whale: WhaleTrader,
    rng: std.Random.DefaultPrng,

    pub fn init(seed: u64) FakeTraderPool {
        var rng = std.Random.DefaultPrng.init(seed);
        const rand = rng.random();

        return .{
            .market_makers = .{
                // Tight spreader, frequent, small size (~0.5 units)
                MarketMaker.init(50_000_000, 5_000_000_000, 3, 1),
                // Wide spreader, less frequent, medium size (~1.5 units)
                MarketMaker.init(150_000_000, 8_000_000_000, 5, 2),
                // Aggressive, very frequent (~0.3 units)
                MarketMaker.init(30_000_000, 3_000_000_000, 2, 1),
            },
            .momentum_traders = .{
                // Fast momentum, frequent checks (~0.8 units)
                MomentumTrader.init(80_000_000, 10_000_000_000, 8 + rand.intRangeAtMost(u16, 0, 4)),
                // Slow momentum, less frequent (~2.0 units)
                MomentumTrader.init(200_000_000, 15_000_000_000, 15 + rand.intRangeAtMost(u16, 0, 5)),
            },
            .mean_rev_traders = .{
                // Tight band (quick to react, ~1.0 units)
                MeanRevTrader.init(100_000_000, 12_000_000_000, 10, 15),
                // Wide band (waits for bigger dislocations, ~3.0 units)
                MeanRevTrader.init(300_000_000, 20_000_000_000, 20, 40),
            },
            .noise_traders = .{
                // Very active noise (~0.2 units)
                NoiseTrader.init(20_000_000, 2_000_000_000, 8),
                NoiseTrader.init(40_000_000, 3_000_000_000, 5),
                // Occasional noise (~0.6 units)
                NoiseTrader.init(60_000_000, 4_000_000_000, 3),
                NoiseTrader.init(15_000_000, 1_500_000_000, 6),
            },
            .whale = WhaleTrader.init(1_000_000_000, 50_000_000_000, 200),
            .rng = rng,
        };
    }

    /// Run all fake traders for one tick. Returns generated trades.
    pub fn onTick(self: *FakeTraderPool, tick: u64, books: *const [8]L2Book) TradeBuffer {
        var buf = TradeBuffer.init();
        const rand = self.rng.random();

        for (&self.market_makers) |*mm| mm.onTick(tick, rand, books, &buf);
        for (&self.momentum_traders) |*mt| mt.onTick(tick, rand, books, &buf);
        for (&self.mean_rev_traders) |*mr| mr.onTick(tick, rand, books, &buf);
        for (&self.noise_traders) |*nt| nt.onTick(tick, rand, books, &buf);
        self.whale.onTick(tick, rand, books, &buf);

        return buf;
    }
};

// ─── Tests ───────────────────────────────────────────────────────────────────

test "fake_trader_pool_init" {
    const pool = FakeTraderPool.init(42);
    // Verify initial state
    for (pool.market_makers[0].inventory) |inv| {
        try std.testing.expectEqual(@as(i64, 0), inv);
    }
    try std.testing.expectEqual(@as(i64, 0), pool.whale.iceberg_remaining);
}

test "fake_trader_pool_generates_trades" {
    const allocator = std.testing.allocator;

    var books: [8]L2Book = undefined;
    var init_count: usize = 0;
    errdefer for (0..init_count) |i| books[i].deinit();

    for (0..8) |i| {
        books[i] = try L2Book.init(allocator, 5);
        init_count += 1;
        // Set up realistic book
        const bids = [_]Level{
            .{ .price = 50_000_000_000 - 100_000, .quantity = 5_000_000 },
            .{ .price = 50_000_000_000 - 200_000, .quantity = 8_000_000 },
            .{ .price = 50_000_000_000 - 300_000, .quantity = 3_000_000 },
        };
        const asks = [_]Level{
            .{ .price = 50_000_000_000 + 100_000, .quantity = 5_000_000 },
            .{ .price = 50_000_000_000 + 200_000, .quantity = 8_000_000 },
            .{ .price = 50_000_000_000 + 300_000, .quantity = 3_000_000 },
        };
        books[i].applySnapshot(&bids, &asks);
    }
    defer for (0..8) |i| books[i].deinit();

    var pool = FakeTraderPool.init(42);

    // Run 100 ticks and count total trades
    var total_trades: u32 = 0;
    for (0..100) |t| {
        const result = pool.onTick(@intCast(t), &books);
        total_trades += result.count;
    }

    // Should generate a meaningful number of trades over 100 ticks
    try std.testing.expect(total_trades > 20);
}

test "market_maker_trades_both_sides" {
    const allocator = std.testing.allocator;

    var books: [8]L2Book = undefined;
    var init_count: usize = 0;
    errdefer for (0..init_count) |i| books[i].deinit();

    for (0..8) |i| {
        books[i] = try L2Book.init(allocator, 5);
        init_count += 1;
        const bids = [_]Level{
            .{ .price = 50_000_000_000 - 100_000, .quantity = 5_000_000 },
        };
        const asks = [_]Level{
            .{ .price = 50_000_000_000 + 100_000, .quantity = 5_000_000 },
        };
        books[i].applySnapshot(&bids, &asks);
    }
    defer for (0..8) |i| books[i].deinit();

    var mm = MarketMaker.init(1_000_000, 50_000_000, 1, 1);
    var rng = std.Random.DefaultPrng.init(123);
    const rand = rng.random();

    var buys: u32 = 0;
    var sells: u32 = 0;
    for (0..200) |t| {
        var buf = TradeBuffer.init();
        mm.onTick(@intCast(t), rand, &books, &buf);
        for (0..buf.count) |i| {
            switch (buf.trades[i].side) {
                .buy => buys += 1,
                .sell => sells += 1,
            }
        }
    }

    // Market maker should trade both sides
    try std.testing.expect(buys > 10);
    try std.testing.expect(sells > 10);
}

test "whale_generates_large_trades" {
    const allocator = std.testing.allocator;

    var books: [8]L2Book = undefined;
    var init_count: usize = 0;
    errdefer for (0..init_count) |i| books[i].deinit();

    for (0..8) |i| {
        books[i] = try L2Book.init(allocator, 5);
        init_count += 1;
        const bids = [_]Level{
            .{ .price = 50_000_000_000 - 100_000, .quantity = 50_000_000 },
        };
        const asks = [_]Level{
            .{ .price = 50_000_000_000 + 100_000, .quantity = 50_000_000 },
        };
        books[i].applySnapshot(&bids, &asks);
    }
    defer for (0..8) |i| books[i].deinit();

    var whale = WhaleTrader.init(10_000_000, 500_000_000, 5);
    whale.cooldown = 0; // Force immediate start
    var rng = std.Random.DefaultPrng.init(777);
    const rand = rng.random();

    var total_volume: i64 = 0;
    var trade_count: u32 = 0;
    for (0..100) |t| {
        var buf = TradeBuffer.init();
        whale.onTick(@intCast(t), rand, &books, &buf);
        for (0..buf.count) |i| {
            total_volume += buf.trades[i].quantity;
            trade_count += 1;
        }
    }

    // Whale should have generated some trades with meaningful volume
    try std.testing.expect(trade_count > 0);
    try std.testing.expect(total_volume > 5_000_000);
}

test "noise_trader_is_random" {
    const allocator = std.testing.allocator;

    var books: [8]L2Book = undefined;
    var init_count: usize = 0;
    errdefer for (0..init_count) |i| books[i].deinit();

    for (0..8) |i| {
        books[i] = try L2Book.init(allocator, 5);
        init_count += 1;
        const bids = [_]Level{
            .{ .price = 50_000_000_000 - 100_000, .quantity = 5_000_000 },
        };
        const asks = [_]Level{
            .{ .price = 50_000_000_000 + 100_000, .quantity = 5_000_000 },
        };
        books[i].applySnapshot(&bids, &asks);
    }
    defer for (0..8) |i| books[i].deinit();

    var nt = NoiseTrader.init(500_000, 50_000_000, 50); // 50% trade probability
    var rng = std.Random.DefaultPrng.init(999);
    const rand = rng.random();

    var instruments_hit = std.mem.zeroes([NUM_INSTRUMENTS]bool);
    for (0..500) |t| {
        var buf = TradeBuffer.init();
        nt.onTick(@intCast(t), rand, &books, &buf);
        for (0..buf.count) |i| {
            instruments_hit[buf.trades[i].instrument_idx] = true;
        }
    }

    // Noise trader should hit multiple instruments
    var hit_count: u8 = 0;
    for (instruments_hit) |hit| {
        if (hit) hit_count += 1;
    }
    try std.testing.expect(hit_count >= 3);
}
